apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
      name: demo
    spec:
      containers:
        - image: nginx:1.23.4-alpine
          name: nginx
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      env: demo
